{{- if .Values.ingress.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainlink.fullname" . }}-ingress-auth
  annotations:
  {{- with .Values.ingress.auth.secret.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  auth: {{ .Values.ingress.auth.authFileContents | quote }}
  password: {{ .Values.ingress.auth.password | quote }}
  username: {{ .Values.ingress.auth.username | quote }}
{{- end -}}