apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainlink.fullname" . }}-node-admin
type: Opaque
stringData:
  apiLogin: "{{ .Values.nodeConfig.apiUser }}\n{{ .Values.nodeConfig.apiPassword }}"
  walletPassword: {{ .Values.nodeConfig.walletPassword | quote }}
