{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chainlink.fullname" . }}
  labels:
    {{- include "chainlink.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'services'
    verbs:
      - 'get'
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - 'get'
    - 'patch'
{{- end }}